# Generated by Django 5.0.14 on 2026-08-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text')], default='image', max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(choices=[('REAL', 'Real'), ('FAKE', 'Fake')], max_length=10)),
                ('confidence', models.FloatField()),
                ('raw_probability', models.FloatField(blank=True, null=True)),
                ('ela_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('gradcam_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('report_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
