# Generated by Django 5.0.14 on 2026-08-25 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_detection_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='certificate_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
