# Generated by Django 5.0.14 on 2026-08-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_detection_certificate_filename_detection_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('document', 'Document'), ('link', 'Link'), ('compare', 'File Comparison')], default='image', max_length=10),
        ),
    ]
