# Generated by Django 5.0.14 on 2026-09-13 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_detection_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('document', 'Document'), ('link', 'Link'), ('compare', 'File Comparison'), ('proctor', 'AI Interview Proctoring')], default='image', max_length=15),
        ),
        migrations.CreateModel(
            name='AgenticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='agent_uploads/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('detected_media_type', models.CharField(blank=True, max_length=32)),
                ('summary_verdict', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgenticMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('agent', 'VeriScan Agent'), ('system', 'Tool System Trace')], max_length=16)),
                ('content', models.TextField()),
                ('thought_trace', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='detection.agenticsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
