# Generated by Django 5.0.14 on 2026-09-14 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_detection_media_type_agenticsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Person/Brand', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredMediaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1024)),
                ('title', models.CharField(max_length=512)),
                ('snippet', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=1024)),
                ('deepfake_result', models.CharField(default='UNVERIFIED', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_sources', to='detection.monitoredtarget')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
    ]
