# Generated by Django 5.0.14 on 2026-09-14 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_monitoredtarget_discoveredmediasource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_query', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='JobListingVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_domain', models.CharField(max_length=255)),
                ('location', models.CharField(default='Remote / Hybrid', max_length=255)),
                ('posted_date', models.CharField(default='Recently', max_length=64)),
                ('apply_url', models.URLField(max_length=1024)),
                ('status', models.CharField(default='REAL', max_length=16)),
                ('confidence', models.FloatField(default=90.0)),
                ('scam_indicators', models.JSONField(blank=True, default=list)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='detection.jobsearchquery')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
