# Generated by Django 5.0.14 on 2026-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_jobsearchquery_joblistingverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistingverification',
            name='source_platform',
            field=models.CharField(default='Official Careers Portal', max_length=255),
        ),
    ]
