# Generated by Django 5.0.14 on 2026-09-14 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_joblistingverification_source_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_input', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_name', models.CharField(max_length=255)),
                ('claimed_company', models.CharField(max_length=255)),
                ('profile_url', models.URLField(blank=True, max_length=1024)),
                ('email_domain', models.CharField(default='unverified', max_length=255)),
                ('authenticity_status', models.CharField(default='LEGITIMATE', max_length=32)),
                ('confidence_score', models.FloatField(default=95.0)),
                ('identity_signals', models.JSONField(blank=True, default=list)),
                ('verified_sources', models.JSONField(blank=True, default=list)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='detection.recruiterquery')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
