# Generated by Django 5.0.14 on 2026-09-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_recruiterquery_recruiterverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('document', 'Document'), ('link', 'Link'), ('compare', 'File Comparison'), ('proctor', 'AI Interview Proctoring'), ('crawler', 'Web & Media Monitor'), ('jobs', 'Job Role Authenticator'), ('recruiter', 'Recruiter Identity Authenticator')], default='image', max_length=15),
        ),
    ]
