# Generated by Django 5.0.14 on 2026-09-13 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('face_verified', 'Face Verified & Registered'), ('face_rejected', 'Duplicate Face Rejected'), ('detection_run', 'Detection Executed'), ('payment_submitted', 'Payment Request Submitted'), ('payment_approved', 'Payment Request Approved'), ('payment_rejected', 'Payment Request Rejected'), ('access_granted', 'Access Granted by Admin'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('user_deleted', 'User Deleted'), ('password_reset', 'Password Reset')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
