# Generated by Django 5.0.14 on 2026-08-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_detections_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='paid_access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
