# Generated by Django 5.0.14 on 2026-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_free_detections_used_user_paid_access_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_descriptor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='face_registered',
            field=models.BooleanField(default=False),
        ),
    ]
